reviews:
  ignore:
    - "**/package-lock.json"
    - "**/yarn.lock"
    - "**/*.csv"
    - "**/*.ipynb"
    - "dist/**"
    - "build/**"
    - "**/*.md"
    - "**/*.bat"
    - "**/*.example"
    - "docker-compose.yml"
    - "docker/**"
